server:
  port: 7003

# Eureka配置
eureka:
  instance:
    hostname: localhost # Eureka服务端的实例名称
  client:
    register-with-eureka: false # 表示是否向Eureka注册中心注册自己
    fetch-registry: false # 如果为false，则表示自己为注册中心
    service-url: # 监控页面
      defaultZone: http://localhost:${server.port}/eureka/,http://localhost:7001/eureka/,http://localhost:7002/eureka/