server:
  port: 80

# Eureka 配置
eureka:
  client:
    register-with-eureka: false # 不向Eureka中注册自己
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/,http://localhost:7003/eureka/