server:
    port: 8081
# rabbitmq
spring:
    rabbitmq:
        username: admin # Ĭguest
        password: admin # guest
        virtual-host: / # Ĭ /
        host: localhost # Ĭlocalhost
        port: 5672 # Ĭ5672

